server:
  port: 8080

spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://localhost:8081
              predicates:
                - Path=/users/**
              filters:
                - StripPrefix=1
            - id: book-service
              uri: http://localhost:8082
              predicates:
                - Path=/books/**
              filters:
                - StripPrefix=1