spring:
  data:
    mongodb:
      database: user_database
      host: localhost
      port: 27017

server:
  port: 8080

jwt:
  token:
    refresh:
      name: "c2FkZmdhc2Vkb1trZmlmZ3BzZXJ0am1yaG9wW3RyaHJydGp0eXVram1neXVpbGh1aW87aW87"
      expiration: 60000
