spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:userdb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format-sql: true

server:
  port: 8080

jwt:
  token:
    name: "c2FkZmdhc2Vkb1trZmlmZ3BzZXJ0am1yaG9wW3RyaHJydGp0eXVram1neXVpbGh1aW87aW87"
    refresh:
      expiration: 60000
    access:
      expiration: 10000
